swagger: "2.0"
info:
  description: "Sample API for the micro-service blueprint project"
  version: "1.0.0"
  title: "Bleuprint API"
  license:
    name: "MIT"
    url: "https://www.mit.edu/~amini/LICENSE.md"
basePath: "/v1"
tags:
  - name: "login"
    description: "User login"
  - name: "register"
    description: "User registration"
  - name: "user"
    description: "Operations about user"
schemes:
  - "https"
  - "http"
paths:
  /login:
    post:
      tags:
        - "user"
        - "login"
      summary: "User login"
      description: ""
      operationId: "login"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User login data"
          required: true
          schema:
            $ref: "#/definitions/UserLogin"
      responses:
        "405":
          description: "Login failed"
definitions:
  UserLogin:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
